server:
  port: 8083

name: abc

# 对象
person:
  name: ${name} # zhangsan
  age: 20
  address:
    - beijing
    - shanghai

# 对象行内写法
person2: { name: zhangsan,age: 20 }

# 数组
address:
  - beijing
  - shanghai

address2: [ beijing,shanghai ]

# 纯量
msg1: 'hello \n world' # ''--不会识别转义字符,会原样输出
msg2: "hello \n world" # ""-- 会识别转义字符