---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: dev

---
# VM options 虚拟机参数设置
# -Dspring.profiles.active=test

# Program arguments  命令行参数设置
# --spring.profiles.active=pro
# java -jar springboot-profiles-0.0.1-SNAPSHOT.jar --spring.profiles.active=pro
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: test

---
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: pro

---
spring:
  profiles:
    active: dev

